Repository Niklas-Seppala/SpotifyMap, pull requests merged in 2022-04, with the labels that each got.

#3 Implement reverse geocode, display user's current location, make current location button
  SpotifyMap.xcodeproj/project.pbxproj
  SpotifyMap.xcodeproj/project.xcworkspace/xcuserdata/iosdev.xcuserdatad/UserInterfaceState.xcuserstate
  SpotifyMap/Views/HomeView.swift
  SpotifyMap/Views/MapViewModel.swift
Labels: enhancement

#11 get permission and display location on HomeView render, fixed region …
  SpotifyMap.xcodeproj/project.xcworkspace/xcuserdata/iosdev.xcuserdatad/UserInterfaceState.xcuserstate
  SpotifyMap/Views/HomeView.swift
  SpotifyMap/Views/MapViewModel.swift
Labels: bug, enhancement

#25 localization to Finnish done
  SpotifyMap.xcodeproj/project.pbxproj
  SpotifyMap/Views/HomeView.swift
  SpotifyMap/Views/LandingView.swift
  SpotifyMap/Views/en.lproj/Localizable.strings
  SpotifyMap/Views/fi.lproj/Localizable.strings
Labels: Subtask

#39 Search songs UI + remove current location button + fix HomeView loading state logic
  SpotifyMap/Assets.xcassets/SearchPlaceholder.imageset/Contents.json
  SpotifyMap/Assets.xcassets/SearchPlaceholder.imageset/SearchPlaceholder.png
  SpotifyMap/Services/Api/BackendApi.swift
  SpotifyMap/Services/RequestManager.swift
  SpotifyMap/Views/HomeView.swift
  SpotifyMap/Views/SearchView.swift
  SpotifyMap/Views/Subviews/SongList.swift
Labels: bug, enhancement

#50 Spotify interop
  SpotifyMap.xcodeproj/project.pbxproj
  SpotifyMap/Services/Api/SpotifyApi.swift
  SpotifyMap/Services/AuthManager.swift
  SpotifyMap/Services/ToastUtils.swift
  SpotifyMap/Utils/Errors.swift
  SpotifyMap/Views/ContentView.swift
  SpotifyMap/Views/HomeView.swift
  SpotifyMap/Views/LandingView.swift
  SpotifyMap/Views/SearchView.swift
  SpotifyMap/Views/Subviews/SongList.swift
  SpotifyMap/Views/Subviews/SpotifyAuthButton.swift
  SpotifyMap/Views/Subviews/SpotifyFavButton.swift
  SpotifyMap/Views/Subviews/SpotifyTrackWebView.swift
  SpotifyMap/Views/Subviews/VisitorAuthButton.swift
Labels: enhancement
